# StarVulkanPch.cmake
#
# Reusable precompiled-header setup shared across the Starlight targets.
#
# Generates two PCH source files (vulkan_pch.hpp + commons_pch.hpp) once into
# ${CMAKE_BINARY_DIR}/pch and attaches them to a target so that target compiles
# its OWN PCH from the shared source. Each target therefore compiles a PCH with
# its own defines -- no REUSE_FROM, no MSVC C4651/C4652 define-mismatch warnings.
#
# Usage:
#   # once, from starlight's CMakeLists.txt (starlight is added first):
#   include("${CMAKE_CURRENT_SOURCE_DIR}/cmake/StarVulkanPch.cmake")
#   star_add_pch(${STARLIGHT_NAME})
#
#   # from any other Starlight target added after starlight:
#   if(COMMAND star_add_pch)
#       star_add_pch(<target>)
#   endif()
#
# Keep the generated contents LEAN and STABLE: every TU of a target recompiles
# whenever this content changes, and any macro that affects a header here must
# be defined identically for all callers (set such macros via
# target_compile_definitions, never per-TU #define). <glm/...> is intentionally
# NOT included here: GLM is sensitive to GLM_FORCE_DEPTH_ZERO_TO_ONE, which only
# some targets define.

include_guard(GLOBAL)

# Write a file only when its content would change, so re-running configure does
# not bump the file mtime and force a full PCH (and therefore full) rebuild.
function(star_pch_write_if_changed path content)
    if(EXISTS "${path}")
        file(SHA256 "${path}" _star_pch_old)
    else()
        set(_star_pch_old "")
    endif()
    string(SHA256 _star_pch_new "${content}")
    if(NOT _star_pch_new STREQUAL _star_pch_old)
        file(WRITE "${path}" "${content}")
    endif()
endfunction()

# Generate (idempotently) the shared PCH sources and attach them to <target>.
function(star_add_pch target)
    set(STAR_PCH_DIR "${CMAKE_BINARY_DIR}/pch")

    set(_vulkan_content
"// Auto-generated by CMake (extern/starlight/cmake/StarVulkanPch.cmake). Do not edit.
#pragma once

// --- Vulkan (C++ bindings) + VMA ---
#include <vulkan/vulkan.hpp>
#include <vk_mem_alloc.h>
")
    star_pch_write_if_changed("${STAR_PCH_DIR}/vulkan_pch.hpp" "${_vulkan_content}")

    set(_commons_content
"// Auto-generated by CMake (extern/starlight/cmake/StarVulkanPch.cmake). Do not edit.
#pragma once

// --- Standard library (common, stable) ---
#include <algorithm>
#include <array>
#include <atomic>
#include <cassert>
#include <chrono>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <map>
#include <memory>
#include <mutex>
#include <numeric>
#include <optional>
#include <set>
#include <span>
#include <string>
#include <thread>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>

// --- JSON ---
#include <nlohmann/json.hpp>

// --- Abseil (pervasive container) ---
#include <absl/container/flat_hash_map.h>
")
    star_pch_write_if_changed("${STAR_PCH_DIR}/commons_pch.hpp" "${_commons_content}")

    target_precompile_headers(${target} PRIVATE
        "$<$<COMPILE_LANGUAGE:CXX>:${STAR_PCH_DIR}/vulkan_pch.hpp>"
        "$<$<COMPILE_LANGUAGE:CXX>:${STAR_PCH_DIR}/commons_pch.hpp>"
    )
endfunction()