# Shared, auto-generated precompiled header for the Starlight targets.
#
# Generates two PCH source files at configure time and attaches them to the
# `starlight` target. The other Starlight targets (compute_volumetrics_lib,
# terrain, windowing) reuse the compiled PCH artifact via:
#
#     target_precompile_headers(<target> REUSE_FROM starlight)
# The generated headers are written to ${CMAKE_CURRENT_BINARY_DIR}/pch (build
# tree), which is already covered by the out/* / build/* gitignore entries.
# Write a file only when its content would change, so re-running configure does
# not bump the file mtime and force a full PCH (and therefore full) rebuild.
function(star_pch_write_if_changed path content)
    if(EXISTS "${path}")
        file(SHA256 "${path}" _star_pch_old)
    else()
        set(_star_pch_old "")
    endif()
    string(SHA256 _star_pch_new "${content}")
    if(NOT _star_pch_new STREQUAL _star_pch_old)
        file(WRITE "${path}" "${content}")
    endif()
endfunction()

set(STAR_PCH_DIR "${CMAKE_CURRENT_BINARY_DIR}/pch")
# Kept as a cache flag so consumers can guard with:
#   if(TARGET starlight AND STAR_VULKAN_PCH_HEADER)
set(STAR_VULKAN_PCH_HEADER "${STAR_PCH_DIR}/vulkan_pch.hpp" CACHE FILEPATH
    "Auto-generated precompiled header (shared across Starlight targets)")

set(_STAR_VULKAN_PCH_CONTENT
"// Auto-generated by CMake (extern/starlight/cmake/StarVulkanPch.cmake). Do not edit.
#pragma once

// --- Vulkan (C++ bindings) + VMA ---
#include <vulkan/vulkan.hpp>
#include <vk_mem_alloc.h>
")
star_pch_write_if_changed("${STAR_PCH_DIR}/vulkan_pch.hpp" "${_STAR_VULKAN_PCH_CONTENT}")

set(_STAR_COMMONS_PCH_CONTENT
"// Auto-generated by CMake (extern/starlight/cmake/StarVulkanPch.cmake). Do not edit.
#pragma once

// --- Standard library (common, stable) ---
#include <algorithm>
#include <array>
#include <atomic>
#include <cassert>
#include <chrono>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <map>
#include <memory>
#include <mutex>
#include <numeric>
#include <optional>
#include <set>
#include <span>
#include <string>
#include <thread>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <variant>
#include <vector>

// --- JSON ---
#include <nlohmann/json.hpp>

// --- Abseil (pervasive container) ---
#include <absl/container/flat_hash_map.h>
")
star_pch_write_if_changed("${STAR_PCH_DIR}/commons_pch.hpp" "${_STAR_COMMONS_PCH_CONTENT}")

target_precompile_headers(${STARLIGHT_NAME}
    PRIVATE
        "$<$<COMPILE_LANGUAGE:CXX>:${STAR_PCH_DIR}/vulkan_pch.hpp>"
        "$<$<COMPILE_LANGUAGE:CXX>:${STAR_PCH_DIR}/commons_pch.hpp>"
)